name: Publish GH copy
on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write

jobs:
  wasi_job:
    runs-on: ubuntu-latest
    name: WASI module
    steps:
    - uses: actions/checkout@v3

    - name: WASI flite step
      run: |
        sudo apt-get -y install clang libasound2-dev
        wget -q https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-16/wasi-sdk_16.0_amd64.deb
        sudo dpkg -i wasi-sdk_16.0_amd64.deb
        git clone -b wavstdout --depth=1 https://github.com/shrmpy/flite.git
        cd flite
        ./configure --host=wasm32-wasi CC=clang AR=/opt/wasi-sdk/bin/llvm-ar RANLIB=/opt/wasi-sdk/bin/llvm-ranlib
        make

    - name: WASI artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wasi-flite
        retention-days: 1
        path: |
          flite/bin/wav_stdout

  archive_job:
    needs: wasi_job
    runs-on: ubuntu-latest
    name: Archive 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: wasi-flite
        path: tmp
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'

    - name: WASM target step
      run: |
        mv tmp/wav_stdout dist/flite.wasm
        GOOS=js GOARCH=wasm go generate

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ebiten-ghpages
        retention-days: 1
        path: |
          dist/web/
          LICENSE

  publish_job:
    needs: archive_job
    if: github.ref == 'refs/heads/main'
    name: Pub to GH pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ebiten-ghpages

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: dist/web
